### PR TITLE
Tool toggle

### PR DESCRIPTION
**Pull request by magnus-ISU**
Toggle on/off rendering of tools and armor individually

Unsure if using the exact right way, as `reallyDraw` seemed unused. Double check it

### CODE REVIEW

**Comment by magnus-ISU** [comment]
Anything you want me to do before this is merged? I know you said you're waiting for the next update to update the binary, but I don't like having outstanding PRs as I will forget about it.

**Comment by HyPeRXKo** [comment]
I really would like that but it seems that it wasn't merge in two months :(

**Comment by magnus-ISU** [comment]
If you need a binary (I might have made other changes, I forget, but probably not?) https://github.com/magnus-ISU/clientside-mods/blob/master/mods/durabilityviewer-1.19-fabric0.53.3-1.10.3.jar

**Comment by the-r3dacted** [comment]
Can you make a 1.16.5 binary?

**Comment by gbl** [comment]
Sorry, somehow I totally missed that this is a PR, not just a feature request. And then I stopped updating my mods as I'm not playing anymore. Unfortunately, this won't merge into the 1.20 version as the whole rendering code has changed.

**Pull request closed without merging**
